import {
  authenticateParticipantDefinition,
  createPersistentContactAssociationDefinition,
  loadContactContentDefinition,
  associateContactToCustomerProfileDefinition,
  checkOutboundCallStatusDefinition,
  checkVoiceIdDefinition,
  connectParticipantWithLexBotDefinition,
  completeOutboundCallDefinition,
  createCaseDefinition,
  createCallbackContactDefinition,
  createCustomerProfileDefinition,
  createTaskDefinition,
  createWisdomSessionDefinition,
  evaluateDataTableValuesDefinition,
  checkHoursOfOperationDefinition,
  checkMetricDataDefinition,
  compareDefinition,
  dequeueContactAndTransferToQueueDefinition,
  disconnectParticipantDefinition,
  transferContactToQueueDefinition,
  transferParticipantToThirdPartyDefinition,
  distributeByPercentageDefinition,
  endFlowExecutionDefinition,
  endFlowModuleExecutionDefinition,
  getCaseDefinition,
  getCalculatedAttributesForCustomerProfileDefinition,
  getCustomerProfileDefinition,
  getCustomerProfileObjectDefinition,
  listDataTableValuesDefinition,
  getParticipantInputDefinition,
  getMetricDataDefinition,
  invokeLambdaFunctionDefinition,
  invokeFlowModuleDefinition,
  loopDefinition,
  messageParticipantDefinition,
  messageParticipantIterativelyDefinition,
  resumeContactDefinition,
  showViewDefinition,
  startOutboundChatContactDefinition,
  startVoiceIdStreamDefinition,
  tagContactDefinition,
  transferContactToAgentDefinition,
  transferToFlowDefinition,
  upsertDataTableValuesDefinition,
  unTagContactDefinition,
  updateContactCallbackNumberDefinition,
  updateContactDataDefinition,
  updateContactEventHooksDefinition,
  updateContactMediaProcessingDefinition,
  updateContactMediaStreamingBehaviorDefinition,
  updateContactRecordingAndAnalyticsBehaviorDefinition,
  updatePreviousContactParticipantStateDefinition,
  updateCaseDefinition,
  updateContactRoutingBehaviorDefinition,
  updateContactTargetQueueDefinition,
  updateContactTextToSpeechVoiceDefinition,
  updateFlowLoggingBehaviorDefinition,
  updateRoutingCriteriaDefinition,
  updateContactAttributesDefinition,
  updateContactRecordingBehaviorDefinition,
  updateFlowAttributesDefinition,
  updateCustomerProfileDefinition,
  waitDefinition,
} from "./actions/index.js";
import type { ActionDefinition } from "./action-definition.js";
import type { FlowActionType } from "./types.js";

export const actionDefinitions = [
  authenticateParticipantDefinition,
  createPersistentContactAssociationDefinition,
  loadContactContentDefinition,
  associateContactToCustomerProfileDefinition,
  checkOutboundCallStatusDefinition,
  checkVoiceIdDefinition,
  connectParticipantWithLexBotDefinition,
  completeOutboundCallDefinition,
  createCaseDefinition,
  createCallbackContactDefinition,
  createCustomerProfileDefinition,
  createTaskDefinition,
  createWisdomSessionDefinition,
  evaluateDataTableValuesDefinition,
  checkHoursOfOperationDefinition,
  checkMetricDataDefinition,
  compareDefinition,
  dequeueContactAndTransferToQueueDefinition,
  disconnectParticipantDefinition,
  transferContactToQueueDefinition,
  transferParticipantToThirdPartyDefinition,
  distributeByPercentageDefinition,
  endFlowExecutionDefinition,
  endFlowModuleExecutionDefinition,
  getCaseDefinition,
  getCalculatedAttributesForCustomerProfileDefinition,
  getCustomerProfileDefinition,
  getCustomerProfileObjectDefinition,
  listDataTableValuesDefinition,
  getParticipantInputDefinition,
  getMetricDataDefinition,
  invokeLambdaFunctionDefinition,
  invokeFlowModuleDefinition,
  loopDefinition,
  messageParticipantDefinition,
  messageParticipantIterativelyDefinition,
  resumeContactDefinition,
  showViewDefinition,
  startOutboundChatContactDefinition,
  startVoiceIdStreamDefinition,
  tagContactDefinition,
  transferContactToAgentDefinition,
  transferToFlowDefinition,
  upsertDataTableValuesDefinition,
  unTagContactDefinition,
  updateContactCallbackNumberDefinition,
  updateContactDataDefinition,
  updateContactEventHooksDefinition,
  updateContactMediaProcessingDefinition,
  updateContactMediaStreamingBehaviorDefinition,
  updateContactRecordingAndAnalyticsBehaviorDefinition,
  updatePreviousContactParticipantStateDefinition,
  updateCaseDefinition,
  updateContactRoutingBehaviorDefinition,
  updateContactTargetQueueDefinition,
  updateContactTextToSpeechVoiceDefinition,
  updateFlowLoggingBehaviorDefinition,
  updateRoutingCriteriaDefinition,
  updateContactAttributesDefinition,
  updateContactRecordingBehaviorDefinition,
  updateFlowAttributesDefinition,
  updateCustomerProfileDefinition,
  waitDefinition,
] as const satisfies readonly ActionDefinition[];

export const supportedActionTypes = actionDefinitions.map(
  (definition) => definition.type,
) as readonly FlowActionType[];

export const actionRegistry = Object.freeze(
  Object.fromEntries(
    actionDefinitions.map((definition) => [definition.type, definition]),
  ) as Record<FlowActionType, ActionDefinition>,
);

export function getActionDefinition(type: FlowActionType): ActionDefinition {
  return actionRegistry[type];
}
